HTML_CSS_Test/test_env/test_env/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("tourism.urls"))
]

HTML_CSS_Test/test_env/tourism/urls.py
from django.urls import path
from . import views

app_name = "tourism"

urlpatterns = [
    path('home/',views.home_page, name="home_page"),
    path('about/saudi/',views.about_sa, name="about_sa"),
    path('riyadh/',views.riyadh_page, name="riyadh_page"),
    path('alula/',views.alula_page, name="alula_page"),
    path('jeddah/',views.jeddah_page, name="jeddah_page"),
    path('abha/',views.abha_page, name="abha_page"),
]

HTML_CSS_Test/test_env/tourism/models.py
from django.db import models

# Create your models here.

class City(models.Model):
    city_name = models.CharField(max_length=2048)
    describtion = models.TextField()

HTML_CSS_Test/test_env/tourism/views.py
from django.shortcuts import render
from django.http import HttpRequest

# Create your views here.

def home_page(request):

    return render(request,"tourism/home.html")

def about_sa(request):

    return render(request,"tourism/about_sa.html")

def riyadh_page(request):

    return render(request,"tourism/riyadh.html")

def alula_page(request):

    return render(request,"tourism/alula.html")

def jeddah_page(request):

    return render(request,"tourism/jeddah.html")

def abha_page(request):

    return render(request,"tourism/abha.html")

HTML_CSS_Test/test_env/tourism/templates/tourism/abha.html
{% extends  'tourism/base.html' %}
{% load static %}

{% block content %}
    <h1>Abha - Explore the Mountains and Culture of the South</h1>
    <p>Abha is the capital of the Asir region, located in the southwest of Saudi Arabia. The city is known for its cool climate, stunning mountainous landscapes, and rich cultural heritage. Explore the beautiful parks and gardens, visit the traditional souks. Abha is also a hub for adventure seekers, with activities such as hiking, rock climbing, and paragliding. The city is home to the famous Abha Palace, a stunning palace complex that offers a glimpse into Saudi Arabia's rich history and culture. With its unique blend of nature and culture, Abha is a destination that is not to be missed.</p>
{% endblock %}


{%block car-content%}
    <div class="wrapper">
        <i id="left" class="fa-solid fa-angle-left" style="color:white;"></i>
        <div class="carousel">
            <img src="{%static 'images/Riyadh-slider.png'%}">
            <img src="{%static 'images/Riyadh-slider2.png'%}">
            <img src="{%static 'images/Riyadh-slider3.png'%}">
            <img src="{%static 'images/Riyadh-slider4.png'%}">
            <img src="{%static 'images/Riyadh-slider5.png'%}">
            <img src="{%static 'images/Riyadh-slider6.png'%}">
        </div>
        <i id="right" class="fa-solid fa-angle-right" style="color:white;"></i>
    </div>
{% endblock %}


{%block city_container%}
    <h1>Activities</h1>
    <p>Visitors of Riyadh Season will enjoy a wonderful time in 15 different entertainment destinations all on the land of the capital, Riyadh. There is a variety of international events, musical concerts, fancy restaurants and many more.</p>
    <div class="row">
        <div class="city_col">
            <img src="{%static 'images/abha-act1.png'%}">
            <h3>Hiking</h3>
            <p>Explore the stunning mountainous landscapes of Abha on foot with a guided hiking tour. From the lush green valleys to the rugged peaks, there is so much to discover in this beautiful region.</p>
        </div>

        <div class="city_col">
            <img src="{%static 'images/abha-act2.png'%}">
            <h3>Heritage Villages</h3>
            <p>Abha is home to several heritage villages that offer a glimpse into the region's rich cultural heritage. Visit the Al-Muftaha Village, a traditional village that has been restored to its former glory, with beautiful old houses and narrow alleys. The Al-Habala Village, located in the mountains, is another must-visit, with its unique architecture and stunning views. The Al-Soudah Heritage Village is also worth exploring, with its traditional buildings and exhibits showcasing the region's history and culture.</p>
        </div>

        <div class="city_col">
            <img src="{%static 'images/abha-act3.png'%}">
            <h3>Paragliding</h3>
            <p>Abha is a hub for adventure seekers, and paragliding is one of the most popular activities in the region. Soar above the stunning mountainous landscapes and take in the breathtaking views of this beautiful region.</p>
        </div>
    </div>
{% endblock %}

HTML_CSS_Test/test_env/tourism/templates/tourism/about_sa.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <title>About Saudi Arabia</title>
        <style>
            * {
                margin:0px;
                padding:0px;
                font-family: 'Ubuntu', sans-serif;
                color: white;
                text-decoration: none;
                scroll-behavior: smooth;
            }

            /* Header styles */
            .header {
                display: flex;
                flex-direction: row;
                justify-content: space-between;
                align-items: center;
                background-image:linear-gradient(rgba(4,9,30,0.6),rgba(4,9,30,0.6)), url("{%static 'images/background.png'%}");
                background-size: cover;
                padding: 18px 35px;
                height: 15vh;
            }
            .menu_bar {
                display: flex;
                flex-direction: row;
                justify-content: space-between;
                column-gap: 25px;   
            }
            .logo{
                color: white ;
            }
            .about-sa{
                
                width: 80%;
                margin: auto;
                padding-top: 80px;
                padding-bottom: 50px;
                

            }
            .row{
                
                display: flex;
                flex-direction: row;
                margin: 30px;
                align-items: center;
                border-radius: 50px;
                overflow: hidden;
                border: 1px solid;
                box-shadow: 5px 10px 18px #888888;
                
            }
            .about-col{
                flex-basis: 48%;
               
                
            }
            .about-col img{
                width: 100%;
                
            }
            .about-col h1{
                padding-top: 0;
                color: chocolate;
                margin-left: 10%;
                margin-right: 10%;
            }
            .about-col p{
                padding: 15px 0 25px;
                margin-left: 10%;
                margin-right: 10%;
                color: black;
            }

            /* Footer styles */
            footer {
            background-color: #333;
            color: #fff;
            padding: 20px;
            text-align: center;
            }

            footer p {
            font-size: 14px;
            }
        </style>

    </head>
    <body>
            <div class="container">
                <div class="header">
                    <h1 class="logo">Travelism</h1>
                    <div class="menu_bar">
                        <a href="{% url 'tourism:home_page' %}">Home</a>
                        <a href="{% url 'tourism:about_sa' %}">Saudi Arabia</a>
                        <a href="{% url 'tourism:home_page' %}">Destination</a>
                        <a href="{% url 'tourism:home_page' %}">About us</a>
                    </div>
                </div>
            </div>   
            <div class="about-sa">
                <div class="row">
                    <div class="about-col">
                        <img src="{%static 'images/about-sa.png'%}" alt="arabic language">
                    </div>
                    <div class="about-col">
                        <h1>Language</h1>
                        <p>Arabic is the official language of Saudi Arabia and the primary language used in all dealings and public transactions. English serves as an informal second language in the Kingdom and is spoken by a large section of its society. All road signs are bilingual, showing information in both Arabic and English. </p>
                    </div>
                </div>
                <div class="row">
                    <div class="about-col">
                        <h1>Culture</h1>
                        <p>Saudi Arabia rich heritage and traditions have been shaped by its position as a historic trade hub and the birthplace of Islam. In recent years, the Kingdom has undergone a significant cultural transformation, evolving centuy-old customs to fit the contemporary world we live in today.</p>
                    </div>
                    <div class="about-col">
                        <img src="{%static 'images/about-sa2.png'%}" alt="Saudi Culture">
                    </div>
                </div>
                <div class="row">
                    <div class="about-col">
                        <img src="{%static 'images/about-sa3.png'%}" alt="arabic language">
                    </div>
                    <div class="about-col">
                        <h1>Exchange and transactions</h1>
                        <p>Currency exchange and transactions are easy in Saudi Arabia. Saudi Arabia national currency is the Saudi riyal (ر.س SAR), which is subdivided into 100 halala. You will receive notes in denominations of five riyals, ten riyals, 50 riyals, 100 riyals and 500 riyals; and coins in one riyal, two riyals, 50 halala, 25 halala, 10 halala, 5 halala and 1 halala.</p>
                    </div>
                </div>
            </div>



        <footer>
            <p>&copy; 2023 Travelism Website</p>
        </footer>
    </body>
    
</html>

HTML_CSS_Test/test_env/tourism/templates/tourism/alula.html
{% extends  'tourism/base.html' %}
{% load static %}

{% block content %}
    <h1>Alula - Immerse Yourself in History and Nature</h1>
    <p>Step back in time and experience the ancient wonders of Alula, a city that has been inhabited for more than 7,000 years. Located in the northwest of Saudi Arabia, Alula offers a unique blend of history, culture, and natural beauty. Explore the magnificent tombs of the Lihyanite kings, stroll through the old town's narrow alleys, and marvel at the stunning rock formations that have been shaped by wind and time. Alula is also a hub for adventure seekers, with activities such as hiking, rock climbing, and paragliding. The crystal-clear waters of the Red Sea offer a wealth of marine life and coral reefs, making it a prime destination for diving and snorkeling. With its rich heritage and natural wonders, Alula is the perfect place to immerse yourself in Saudi Arabia's history and nature.</p>
{% endblock %}


{%block car-content%}
    <div class="wrapper">
        <i id="left" class="fa-solid fa-angle-left" style="color:white;"></i>
        <div class="carousel">
            <img src="{%static 'images/alula-slider.png'%}">
            <img src="{%static 'images/alula-slider2.png'%}">
            <img src="{%static 'images/alula-slider3.png'%}">
            <img src="{%static 'images/alula-slider4.png'%}">
            <img src="{%static 'images/alula-slider5.png'%}">
            <img src="{%static 'images/alula-slider6.png'%}">
            <img src="{%static 'images/alula-slider7.png'%}">
            <img src="{%static 'images/alula-slider8.png'%}">
        </div>
        <i id="right" class="fa-solid fa-angle-right" style="color:white;"></i>
    </div>
{% endblock %}


{%block city_container%}
    <h1>Activities</h1>
    <p>Alula is a paradise for adventure seekers and culture enthusiasts alike. With a wide range of activities and events, there is something for everyone to enjoy. From exploring ancient ruins to soaring above the stunning landscapes in a hot air balloon, Alula has it all.</p>
    <div class="row">
        <div class="city_col">
            <img src="{%static 'images/alula-act1.png'%}">
            <h3>Hiking</h3>
            <p>Explore the stunning landscapes of Alula on foot with a guided hiking tour. From the towering rock formations to the lush green valleys, there is so much to discover in this beautiful region.</p>
        </div>

        <div class="city_col">
            <img src="{%static 'images/alula-act2.png'%}">
            <h3>Diving and Snorkeling</h3>
            <p>Discover the underwater wonders of the Red Sea with a diving or snorkeling excursion in Alula. The crystal-clear waters are home to a diverse range of marine life and coral reefs, making it a prime destination for underwater exploration.</p>
        </div>

        <div class="city_col">
            <img src="{%static 'images/alula-act3.png'%}">
            <h3>Hot Air Balloon Ride</h3>
            <p>Experience the stunning landscapes of Alula from a new perspective with a hot air balloon ride. Soar above the rock formations and valleys as you take in the breathtaking views of this ancient city.</p>
        </div>
    </div>
{% endblock %}

HTML_CSS_Test/test_env/tourism/templates/tourism/base.html
{%load static%}
<!DOCTYPE html>
<html>

        <title>Travelism Explore</title>
        <script src="https://kit.fontawesome.com/75ef6f1513.js" crossorigin="anonymous"></script>
        <script src="{%static 'js/script.js'%}" defer></script>
        <style>
            * {
                margin:0px;
                padding:0px;
                font-family: 'Ubuntu', sans-serif;
                color: white;
                text-decoration: none;
                scroll-behavior: smooth;
            }

            /* Header styles */
            .header {
                display: flex;
                flex-direction: row;
                justify-content: space-between;
                align-items: center;
                background-image:linear-gradient(rgba(4,9,30,0.6),rgba(4,9,30,0.6)), url("{%static 'images/background.png'%}");
                background-size: cover;
                padding: 18px 35px;
                height: 15vh;
            }
            .menu_bar {
                display: flex;
                flex-direction: row;
                justify-content: space-between;
                column-gap: 25px;   
            }
            .logo{
                color: white ;
            }
            /* content styles */
            .content{
                display: flex;
                flex-direction: column;
                width: 80%;
                padding:  0 35px;
                margin-left: 89px;
                margin-top: 50px;

            }
            .content h1{
                color:chocolate;
                margin-bottom: 25px;
                margin-top: 20px;
            }
            .content p{
                color: black;
                font-size: 16px;
                line-height: 150%;
            }
            .content div{
                align-content: center;
            }
            /*carousel styles*/
            .car-content{
                display: flex;
                padding: 0 35px;
                align-items: center;
                justify-content: center;
                min-height: 60vh;
            }
            .wrapper{
                max-width: 1200px;
                position: relative;
            }
            .wrapper i{
                top: 50%;
                height: 46px;
                width: 46px;
                cursor: pointer;
                position: absolute;
                font-size: 1.2rem;
                text-align: center;
                line-height: 46px;
                background-color: chocolate;
                border-radius: 50%;
                transform: translateY(-50%);
            }
            .wrapper i:first-child{
                left: -23px;
                display: none;
            }
            .wrapper i:last-child{
                right: -23px;
            }
            .wrapper .carousel{
                font-size: 0px;
                cursor: pointer;
                overflow: hidden;
                white-space: nowrap;
                scroll-behavior: smooth;
            }
            .carousel .dragging{
                cursor: grab;
                scroll-behavior: auto;
            }
            .carousel .dragging img{
                pointer-events: none;
            }
            .carousel img{
                height: 340px;
                object-fit: cover;
                margin-left: 14px;
                width: calc(100% / 3);
            }
            .carousel img:first-child{
                margin-left: 0px;
            }

            /* Avtivites style */
            .city_container{
                width: 80%;
                margin: auto; 
                padding:  0 35px;
                margin-left: 89px;
                padding-top: 50px;
            }
            .city_container h1{
                color: chocolate;
                font-size: 36px;
                font-weight: 600;
                margin-bottom: 25px;
            }
            .city_container p{
                color: black;
                font-size: 14px;
                font-weight: 300;
                line-height: 22px;
                padding-top: 10px;
                padding-left: 10px;
                padding-right: 10px;
            }
            .row{
                margin: 5%;
                display: flex;
                justify-content: space-between;
            }
            .city_col{
                flex-basis: 31%;
                background: rgba(205,110,30,0.7);
                border-radius: 10px;
                margin-bottom: 5%;
                position: relative;
                overflow: hidden;
                box-sizing: border-box;
                transition: 0.5s;

                
            }
            .city_col h3{
                text-align: center;
                font-weight: 600;
                margin: 20px 0;
            }

            .city_col:hover{
                box-shadow: 0 0 20px 0px rgba(0,0,0,0.2);
            }
            .city_col p{
                margin-bottom: 30px;
                color:#fff
            }
            .city_col img{
                width: 100%;
                display: block;  
            }

        
            /* Footer styles */
            footer {
            background-color: #333;
            color: #fff;
            padding: 20px;
            text-align: center;
            }

            footer p {
            font-size: 14px;
            }


        </style>
    </head>

    <body>
        <div class="container">
            <div class="header">
                <h1 class="logo">Travelism</h1>
                <div class="menu_bar">
                    <a href="{% url 'tourism:home_page' %}">Home</a>
                    <a href="{% url 'tourism:about_sa' %}">Saudi Arabia</a>
                    <a href="{% url 'tourism:home_page' %}">Destination</a>
                    <a href="{% url 'tourism:home_page' %}">About us</a>
                </div>
                
            </div>
        </div>
        <div class="content">
            {% block content %}
                
            {% endblock %}
        </div>
        <div class="car-content">
            {%block car-content%}
               
            {% endblock %}
        </div>

        <div class="city_container">
            {%block city_container%}

            {% endblock %}
        </div>

        <footer>
            <p>&copy; 2023 Travelism Website</p>
        </footer>
    </body>

   
</html>

HTML_CSS_Test/test_env/tourism/templates/tourism/home.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        
        <title>Travelism</title>
        <script src="https://kit.fontawesome.com/75ef6f1513.js" crossorigin="anonymous"></script>
        <style>
            * {
                margin:0px;
                padding:0px;
                font-family: 'Ubuntu', sans-serif;
                color: white;
                text-decoration: none;
                scroll-behavior: smooth;
            }
            .container {
                display: flex;
                flex-direction: column;
                justify-content: start;
                row-gap: 2.5rem;
                background-image:linear-gradient(rgba(4,9,30,0.6),rgba(4,9,30,0.6)), url("https://media.cntraveler.com/photos/61b8fb5605e0328d3acb833c/16:9/w_2560%2Cc_limit/Saudi%2520Arabia_GettyImages-1307891525.jpg");
                background-size:cover;
                min-height: 100vh;
                padding: 18px 35px;
            }
            /* Header styles */
            .header {
                display: flex;
                flex-direction: row;
                justify-content: space-between;
                align-items: center;
                height: 15vh;
            }
            .menu_bar {
                display: flex;
                flex-direction: row;
                justify-content: space-between;
                column-gap: 25px;   
            }
            .logo{
                color: white ;
            }
            /*Content Style*/
            .content{
                width: 90%;
                position: absolute;
                top: 50%;
                left: 50%;
                transform: translate(-50%,-50%);
                text-align: center;
            }
            .content h1{
                font-size: 62px;
                padding-bottom: 10px;
            }
            .hero_btn{
                display:inline-block;
                border: 1px solid #fff;
                padding: 12px 34px;
                font-size: 13px;
                background: transparent;
                position: relative;
                cursor: pointer;
                margin-top: 10px;
            }
            .hero_btn:hover{
                border: 1px solid #ac4407;
                background: #ac4407;
                transition: 1s;
            }

            /*City content*/
            .city_container{
                width: 80%;
                margin: auto; 
                text-align: center;
                padding-top: 100px;
            }
            .city_container h1{
                font-size: 36px;
                font-weight: 600;
            }
            .city_container p{
                color: #777;
                font-size: 14px;
                font-weight: 300;
                line-height: 22px;
                padding: 10px;
            }
            .row{
                margin: 5%;
                display: flex;
                justify-content: space-between;
            }
            .city_col{
                flex-basis: 31%;
                background: #4a3f44;
                border-radius: 10px;
                margin-bottom: 5%;
                padding: 20px 12px;
                box-sizing: border-box;
                transition: 0.5s;

                
            }
            .city_col h3{
                text-align: center;
                font-weight: 600;
                margin: 10px 0;
            }

            .city_col:hover{
                box-shadow: 0 0 20px 0px rgba(0,0,0,0.2);
            }
            .city_col p{
                color:#fff
            }
            /*info container style*/
            .info_container{
                width: 80%;
                margin: auto;
                text-align: center;
                padding-top: 100px;
            }
            .info_container h1{
                margin-bottom: 50px;
            }
            .info_col{
                flex-basis: 24%;
                border-radius: 10px;
                margin-bottom: 30px;
                position: relative;
                overflow: hidden;
            }
            .info_col img{
                width: 100%;
                display: block;  
            }
            .layer{
                background: transparent;
                height: 100%;
                width: 100%;
                position: absolute;
                top: 0;
                left: 0;
                transition: 0.5s;
            }
            .layer:hover{
                background:rgba(100, 74, 77,0.5);
            }
            .layer h3{
                width: 100%;
                font-weight: 500;
                color: #fff;
                font-size: 26px;
                bottom: 0;
                left: 50%;
                transform: translate(-50%);
                position: absolute;
                opacity: 0;
                transition: 0.5s;
            }
            .layer:hover h3{
                bottom: 49%;
                opacity: 1;
            }
            /* about us styles */
            .about_us{
                width: 100%;
                text-align: center;
                padding: 30px 0;
            }
            .about_us h4{
                margin-bottom: 25px;
                margin-top: 20px;
            }
            .icons .fa{
                color: #ac4407;
                margin: 0 13px;
                cursor: pointer;
                padding: 18px 0;
            }

            /* Footer styles */
            footer {
            background-color: #333;
            color: #fff;
            padding: 20px;
            text-align: center;
            }

            footer p {
            font-size: 14px;
            }


        </style>
    </head>

    <body>
        <div class="container">
            <div class="header">
                <h1 class="logo">Travelism</h1>
                <div class="menu_bar">
                    <a href="{% url 'tourism:home_page' %}">Home</a>
                    <a href="{% url 'tourism:about_sa' %}">Saudi Arabia</a>
                    <a href="#destination">Destination</a>
                    <a href="#about">About us</a>
                </div>
                
            </div>

            <div class="content">
                <h1>Discover and enjoy your new places and experiences in Saudi Arabia</h1>
                <a href="{% url 'tourism:about_sa' %}" class="hero_btn">Know more</a>

            </div>
        </div>

        <div id="destination" class="info_container">
            <h1 style="color: black">Popular Destination</h1>
            <p style="color: black">Top tourist hotspots in Saudi Arabia. From the towering skyscrapers of Riyadh to the ancient ruins of Mada'in Saleh.</p>
            <div class="row">
                <div class="info_col">
                    <img src="{%static 'images/Riyadh.png'%}">
                    <div class="layer">
                        <a href="{% url 'tourism:riyadh_page' %}"><h3>Riyadh</h3></a>
                    </div>
                </div>

                <div class="info_col">
                    <img src="{%static 'images/Aula.png'%}">
                    <div class="layer">
                        <a href="{% url 'tourism:alula_page' %}"><h3>Alula</h3></a>
                    </div>
                </div>

                <div class="info_col">
                    <img src="{%static 'images/Jeddah.png'%}" alt="Destination image">
                    <div class="layer">
                        <a href="{% url 'tourism:jeddah_page' %}"><h3>Jeddah</h3></a>
                    </div>
                </div>


                <div class="info_col">
                    <img src="{%static 'images/Abha.png'%}" alt="Destination image">
                    <div class="layer">
                        <a href="{% url 'tourism:abha_page' %}"><h3>Abha</h3></a>
                    </div>
                </div>

            </div>
        </div>
        <div id ="about"class="about_us">
            <h4 style="color: #333;">About Us</h4>
            <p style="color: #333;">Travelism is a website offer a comprehensive guide to the top destinations and experiences in the Kingdom of Saudi Arabia<br>At our core, we are a team of paaionate individuals driven by a common goal; to showcase the beauty and diversity of Saudi Arabia to the world.</p>
            <div class="icons">
                <i class="fa fa-facebook"></i>
                <i class="fa fa-twitter"></i>
                <i class="fa fa-instagram"></i>
                <i class="fa fa-youtube"></i>

            </div>
        </div>
        <footer>
            <p>&copy; 2023 Travelism Website</p>
        </footer>
    </body>

   
</html>

HTML_CSS_Test/test_env/tourism/templates/tourism/jeddah.html
{% extends  'tourism/base.html' %}
{% load static %}

{% block content %}
<h1>Jeddah - A Gateway to the Red Sea</h1>
<p>Located on the western coast of Saudi Arabia, Jeddah is a vibrant and cosmopolitan city that offers a unique blend of old-world charm and modern amenities. Known as the gateway to the Red Sea, Jeddah is a hub for water-based activities such as diving, snorkeling, and fishing. The city is also home to a rich cultural heritage, with historic sites such as the Al-Balad district, a UNESCO World Heritage Site, and the Jeddah Corniche, a popular waterfront promenade. Jeddah is also a foodie's paradise, with a wide range of international and local cuisines to tantalize your taste buds. From the bustling souks to the modern malls, Jeddah is a city that has something for everyone.</p>
{% endblock %}


{%block car-content%}
<div class="wrapper">
    <i id="left" class="fa-solid fa-angle-left" style="color:white;"></i>
    <div class="carousel">
        <img src="{%static 'images/Riyadh-slider.png'%}">
        <img src="{%static 'images/Riyadh-slider2.png'%}">
        <img src="{%static 'images/Riyadh-slider3.png'%}">
        <img src="{%static 'images/Riyadh-slider4.png'%}">
        <img src="{%static 'images/Riyadh-slider5.png'%}">
        <img src="{%static 'images/Riyadh-slider6.png'%}">
    </div>
    <i id="right" class="fa-solid fa-angle-right" style="color:white;"></i>
</div>
{% endblock %}


{%block city_container%}
    <h1>Activities</h1>
    <p>Jeddah is a city that offers a wide range of activities and experiences for visitors to enjoy. From exploring historic sites to indulging in water-based activities, there is never a dull moment in Jeddah.</p>
    <div class="row">
        <div class="city_col">
            <img src="{%static 'images/alula-act2.png'%}" style="height: 150px; background-size: cover;">
            <h3>Snorkeling and Diving</h3>
            <p>Explore the stunning underwater world of the Red Sea with a snorkeling or diving excursion in Jeddah. The crystal-clear waters are home to a diverse range of marine life and coral reefs, making it a prime destination for underwater exploration.</p>
        </div>

        <div class="city_col">
            <img src="{%static 'images/jeddah-act2.png'%}"style="height: 150px; background-size: cover;">
            <h3>Historic Sites</h3>
            <p>Discover Jeddah's rich cultural heritage with a visit to its manyhistoric sites. Explore the Al-Balad district, a UNESCO World Heritage Site, and wander through its narrow streets lined with beautiful old houses. Visit the Jeddah Corniche, a popular waterfront promenade that offers stunning views of the Red Sea and the city's skyline.</p>
        </div>

        <div class="city_col">
            <img src="{%static 'images/jeddah-act3.png'%}">
            <h3>Fishing</h3>
            <p>Jeddah is a popular destination for fishing enthusiasts, with a wide range of fishing charters and tours available. Whether you're a seasoned angler or a beginner, Jeddah offers a variety of fishing experiences for all levels.</p>
        </div>
    </div>
{% endblock %}