Tourism/Guide/urls.py
from django.urls import path
from . import views

app_name = "Guide"

urlpatterns = [
    path("", views.home_page,name="home_page"),
    path("city/al-ula/", views.ula, name="al-ula"),
    path("city/damam/", views.dammam, name="damam"),
    path("city/jeddah/", views.jeddah, name="jeddah"),
    path("city/riyadh/", views.riyadh, name="riyadh")
]

Tourism/Tourism/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("Guide.urls"))
]

Tourism/cities_app/urls.py
from django.urls import path
from . import views

app_name = "cities_app"

urlpatterns = [ 
    path("", views.home_page, name="home_page"),
    path("city/riyadh/",views.riyadh_page,name="riyadh_page"),
    path("city/hail/",views.hail_page,name="hail_page"),
    path("city/mekkah/",views.mekkah_page,name="mekkah_page"),
    path("city/alula/",views.alula_page,name="alula_page"),
]

Tourism/Guide/views.py
from django.shortcuts import render,resolve_url,redirect
from django.http import HttpRequest

def home_page(request:HttpRequest):
    return render(request, "Guide/home.html")

def ula(request:HttpRequest):
    return render(request, "Guide/al-ula.html")
   
def dammam(request:HttpRequest):
    return render(request, "Guide/damam.html")

def jeddah(request:HttpRequest):
    
    return render(request, "Guide/jeddah.html")

def riyadh(request:HttpRequest):
    return render(request, "Guide/riyadh.html")


# Create your views here.

Tourism/cities_app/views.py
from django.shortcuts import render
from django.http import HttpRequest,HttpResponse

def home_page(request:HttpRequest):
    return render(request,"cities_app/home_page.html")

def riyadh_page(request:HttpRequest):
    return render(request,"cities_app/riyadh_page.html")

def hail_page(request:HttpRequest):
    return render(request,"cities_app/hail_page.html")

def alula_page(request:HttpRequest):
    return render(request,"cities_app/alula_page.html")

def mekkah_page(request:HttpRequest):
    return render(request,"cities_app/mekkah_page.html")

Tourism/Guide/templates/Guide/al-ula.html
{% extends 'Guide/home.html' %}
{% load static %}

{% block title %} Saudi Arabia: Al-Ula {% endblock %}
{% block BGimage %} /static/images/pexels-photo-11118464.jpeg{% endblock %}

{% block phrase %} Welcome to Al-Ula saudi's best site for tourism {% endblock %}
{% block cont %} Al-Ula offers the most unique experince to see, from the desert to the mountains {% endblock %}
{% block cont2 %} it offers tons of varity from camping, visiting the herqa cities, and enjoying the sceneries. And here are some pictures: {% endblock %}

{% block img1 %} <img class = "pics1" src="https://images.pexels.com/photos/11026901/pexels-photo-11026901.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"> Mountains: Al-Ula {% endblock %}
{% block img2 %} <img class = "pics2" src="https://images.pexels.com/photos/3889891/pexels-photo-3889891.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"> Desert: Al-Ula {% endblock %}
{% block img13 %} <img class = "pics3" src="https://artdesignasia.com/wp-content/uploads/2020/12/Maraya-concert-hall-1155x770.jpg"> Glass Building: Al-Ula {% endblock %}
{% block img4 %} <img class = "pics4" src="https://upload.wikimedia.org/wikipedia/commons/9/93/Al_Ula_old_town%2C_Saudi_Arabia_2011.jpg"> OldTown: Al-Ula {% endblock %}
{% block footerp %} <p style="color: white; font-family: 'Roboto', sans-serif; font-size: medium;" > Experince Al-Ula: </p>{% endblock %} 
{% block footervid %} <iframe class="video" width="560" height="315" src="https://www.youtube.com/embed/XrM5Y5ghEHQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>{% endblock %}
				

Tourism/Guide/templates/Guide/damam.html
{% extends 'Guide/home.html' %}
{% load static %}

{% block title %} Saudi Arabia: Damam {% endblock %}
{% block BGimage %} /static/images/pexels-usef-ateyah-14148654.jpg{% endblock %}
{% block phrase %} Welcome to Damam saudi's crown jewel in the eastren front {% endblock %}
{% block cont %} Damam offfers the range of enjoying urban city to a beach to a desert {% endblock %}
{% block cont2 %} it offers tons of activities from visiting the beach, or the oldtowns, or mixing with the residents. And here are some pictures: {% endblock %}

{% block img1 %} <img class = "pics1" src="https://i.pinimg.com/originals/91/a6/c3/91a6c32ba173ea379fd99d9f3a6547a9.jpg"> Dammam in 1980* {% endblock %}
{% block img2 %} <img class = "pics2" src="https://media-cdn.tripadvisor.com/media/photo-s/15/d7/40/de/photo4jpg.jpg"> OldTown {% endblock %}
{% block img13 %} <img class = "pics3" src="https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/7f/be/78/for-some-reasons-while.jpg?w=1200&h=900&s=1"> Reef {% endblock %}
{% block img4 %} <img class = "pics4" src="https://media.istockphoto.com/id/1162594434/photo/beautiful-sunrise-view-at-dammam-al-khobar-corniche-saudi-arabia.jpg?s=612x612&w=0&k=20&c=e-9--7ferlTiW0esnGIqZim1nOkwD15xLJ9cilFTbRQ="> Beach {% endblock %}
{% block footerp %} <p style="color: white; font-family: 'Roboto', sans-serif; font-size: medium;" > Experince Al-Dammam: </p>{% endblock %} 
{% block footervid %} <iframe width="560" height="315" src="https://www.youtube.com/embed/sw-i-GUU4Bk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>{% endblock %}

Tourism/Guide/templates/Guide/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Saudi Arabia{% endblock %}</title>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200">
	<link rel="stylesheet" href="{% static 'style/main1.css' %}">
</head>
<body style="background-image: url('{% block BGimage %}static/images/Background.jpg{% endblock %}'); background-size: cover;">
	<section class="fade-in">
		
	  
		<div class="container">
			<div class="bar">
				<img class="logo" src="{% static 'images/saudi-tourism-authority-logo-278AE009B2-seeklogo.com.png' %}" alt="Tourism Logo">
				<div class="nav-bar">
					<span class="material-symbols-outlined">open_in_new</span>
					<a style="color: whitesmoke;" href="{% url 'Guide:al-ula' %}">Al-Ula</a>
					<a style="color: whitesmoke;" href="{% url 'Guide:damam' %}">Damam</a>
					<a style="color: whitesmoke;" href="{% url 'Guide:jeddah' %}">Jeddah</a>
					<a style="color: whitesmoke;" href="{% url 'Guide:riyadh' %}">Riyadh</a>
				</div>
				<div class="top-right">
					<a style="color:white;" href="{% url 'Guide:home_page' %}">Home</a>
					<a style="color:white;" href="">Contact</a>
				</div>
			</div>
			<div class="phara">
				<p>{% block phrase %}Welcome to Saudi Arabia where the impossible is a standard{% endblock %}</p>
				<p>{% block cont %}It's one of the Middle East's biggest countries and the home to a unique culture and the birthplace of the Islamic religion.{% endblock %}</p>
			</div>
			
			
			<div class="cont">
				<p>{% block cont2 %}It's rich in nature with a lot of variation, and here are some pictures:{% endblock %}</p>
				<div class="places-pic">
					<a style="color: aliceblue;" href="{% url 'Guide:al-ula' %}">
						{% block img1 %}
						<img class="pics1" src="https://images.pexels.com/photos/13137654/pexels-photo-13137654.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Al-Ula">Northren Reigon: Al-Ula
						{% endblock %}
					</a>
					<a style="color: aliceblue;" href="{% url 'Guide:damam' %}">
						{% block img2 %}
						<img class="pics2" src="https://images.pexels.com/photos/4533239/pexels-photo-4533239.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Damam in 1980*">Eastren Reigon: Dammam in 1980*
						{% endblock %}
					</a>
					<a style="color: aliceblue;" href="{% url 'Guide:jeddah' %}">
						{% block img13 %}
						<img class="pics3" src="https://images.pexels.com/photos/15612136/pexels-photo-15612136/free-photo-of-a-mosaic-pavement-and-traditional-buildings-in-a-desert-town.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Jeddah">Westren Reigon: Jeddah
						{% endblock %}
					</a>
					<a style="color: aliceblue;" href="{% url 'Guide:riyadh' %}">
						{% block img4 %}
						<img class="pics4" src="https://images.pexels.com/photos/7107495/pexels-photo-7107495.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Riyadh">Centeral Reigon: Riyadh
						{% endblock %}
					</a>
				</div>
				<div class="footer">
					{% block footerp %} <p style="color: white; font-family: 'Roboto', sans-serif; font-size: medium;" > Brief video: </p> {% endblock %}
					{% block footervid %} <iframe width="560" height="315" src="https://www.youtube.com/embed/ollH45NDXu0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>{% endblock %}
				</div>
			</div>


		</div>
	</section>
	<script>
		const element = document.querySelector('.fade-in');
		
		function isInViewport(element) {
		  const rect = element.getBoundingClientRect();
		  return (
			rect.top >= 0 &&
			rect.left >= 0 &&
			rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
			rect.right <= (window.innerWidth || document.documentElement.clientWidth)
		  );
		}
		
		function handleScroll() {
		  if (isInViewport(element)) {
			element.classList.add('fade-in-animation');
			window.removeEventListener('scroll', handleScroll);
		  }
		}
		
		window.addEventListener('scroll', handleScroll);
		</script>
</body>
</html>

Tourism/Guide/templates/Guide/jeddah.html
{% extends 'Guide/home.html' %}
{% load static %}

{% block title %} Saudi Arabia: Jeddah {% endblock %}
{% block BGimage %} /static/images/RFY3MEI7ESNI3SDD4LVPNYPF6M.jpg {% endblock %}
{% block phrase %} Welcome to Jeddah saudi's biggest culture colision in the continent {% endblock %}
{% block cont %} Jeddah offers a view on the heritage of architicture in this reigon, with spectactuluar enviroment {% endblock %}
{% block cont2 %} it offers tons of variation in terms of places to visit. From visiting the OldTown, to visiting the dome and beach of jeddah, and enjoying the unique experince to saudi's one of oldest places. And here are some pictures: {% endblock %}

{% block img1 %} <img class = "pics1" src="https://images.pexels.com/photos/4614473/pexels-photo-4614473.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"> Beach {% endblock %}
{% block img2 %} <img class = "pics2" src="https://destinationksa.com/wp-content/uploads/2015/12/paleblueblog.com_.jpg"> Bazaar {% endblock %}
{% block img13 %} <img class = "pics3" src="https://media.cntraveler.com/photos/61dc4ef2124c14f95cd3cedc/16:9/w_2560%2Cc_limit/Traditional%2520apartment%2520building%2520in%2520the%2520historic%2520Al-Balad%2520district%2520of%2520Jeddah_GettyImages-936583462.jpg"> OldTown {% endblock %}
{% block img4 %} <img class = "pics4" src="https://www.agoda.com/wp-content/uploads/2019/05/What-to-do-in-Jeddah-modern-things-to-see-Al-Rahma-Mosque.jpg"> Mosque {% endblock %}
{% block footerp %} <p style="color: white; font-family: 'Roboto', sans-serif; font-size: medium;" > Experince Al-Balad: </p>{% endblock %} 
{% block footervid %} <iframe width="560" height="315" src="https://www.youtube.com/embed/9dTyE3rOCPg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>{% endblock %}

Tourism/Guide/templates/Guide/riyadh.html
{% extends 'Guide/home.html' %}
{% load static %}

{% block title %} Saudi Arabia: Riyadh {% endblock %}
{% block BGimage %} /static/images/IMG_8272-2-1.webp {% endblock %}

{% block phrase %} Welcome to Riyadh saudi's Capital and crown jewel {% endblock %}
{% block cont %} Riyadh offers tons of activities, places to visit and see from reigon's heritage to modernized enviroments {% endblock %}
{% block cont2 %} from visiting the Bujairi, to Boulevard world, and the famous Edge of the world. And here are some pictures: {% endblock %}

{% block img1 %} <img class = "pics1" src="https://static8.depositphotos.com/1003109/831/i/600/depositphotos_8317742-stock-photo-al-mamlaka-towetr.jpg"> Down Town {% endblock %}
{% block img2 %} <img class = "pics2" src="https://www.timeoutriyadh.com/cloud/timeoutriyadh/2022/10/21/Riyadh-City-Boulevard.jpg"> Boulevard {% endblock %}
{% block img13 %} <img class = "pics3" src="https://www.visitsaudi.com/content/dam/saudi-tourism/media/riyadh-articles/edge-of-the-world.jpg"> Edge of the world {% endblock %}
{% block img4 %} <img class = "pics4" src="https://welcomesaudi.com/uploads/0000/1/2023/01/31/bujairi-terrace-diriyah-restaurants.jpg"> Bujairi {% endblock %}
{% block footerp %} <p style="color: white; font-family: 'Roboto', sans-serif; font-size: medium;" > Experince Al-Riyadh: </p>{% endblock %} 
{% block footervid %} <iframe width="560" height="315" src="https://www.youtube.com/embed/99sruDMY_4A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>{% endblock %}

Tourism/cities_app/templates/cities_app/alula_page.html
{% extends  'cities_app/base2.html' %}
<!-- Page Name -->
{% block title %} Alula City {% endblock%}
<!-- background image -->
{% block bgImage%} /static/images/alulaCity.jpg {% endblock %}
<!-- Main Phrase -->
{% block catchyPhrase %}Where heritage and luxury{% endblock %}
<!-- Sub Phrase -->
{% block details %}<span style="color: #00b6d6;">AlUla</span> is home to Saudi Arabia’s first UNESCO World Heritage Site, deep in the desert in the northwestern region of the country, you might still be able to play out your fantasy of being an intrepid archaeologist for a day.{% endblock %}
<!-- Places Pictures -->
{% block bgPlace1%}/static/images/azimuthFestival.jpg{%endblock%}
{% block bgPlace2%}/static/images/elephantRock.jpg{%endblock%}
{% block bgPlace3%}/static/images/daimumahPark.jpg{%endblock%}
{% block bgPlace4%}/static/images/theOasis.jpg{%endblock%}
<!-- Places Names -->
{%block place1%}Azimuth Festival{% endblock %}
{%block place2%}Elephant Rock{% endblock %}
{%block place3%}Daimumah Park{% endblock %}
{%block place4%}The Oasis{% endblock %}

Tourism/cities_app/templates/cities_app/base1.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} {% endblock %}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'styles/styles.css' %}" />
        <style>
        
            .banner{
                width: 100%;
                height: 100vh;
                background: linear-gradient(rgba(0,0,0,0.65),rgba(0,0,0,0.65)),url("{% block bgImage %} {% endblock %}");
                background-size: cover;
                background-position: center;
            }
        </style>
    {% block head %} {% endblock %}
    </head>
    <body>
        <div class="banner">
            <div class="nav-bar">
                <a href="{% url 'cities_app:home_page' %}"><img src="/static/images/logo1.png" class="logo"></a>
                <ul>
                    <li><a href="{% url 'cities_app:home_page' %}">Home</a></li>
                    <li><a href="{% url 'cities_app:riyadh_page' %}">Riyadh</a></li>
                    <li><a href="{% url 'cities_app:mekkah_page' %}">Mekkah</a></li>
                    <li><a href="{% url 'cities_app:hail_page' %}">Hail</a></li>
                    <li><a href="{% url 'cities_app:alula_page' %}">AlUla</a></li>
                </ul>
            </div>
            <div class="content">
            {% block content %} {% endblock %}
            </div>
        </div>
    </body>
</html>

Tourism/cities_app/templates/cities_app/base2.html
{% extends  'cities_app/base1.html' %}
{% load static %}

{% block title %}{% endblock%}
{% block head %}
<style>

.row{
    padding-left: 8%;
    display: flex;
    height: 88%;
    font-size: 13px;
}

.col{
    flex-basis: 50%;
}
.col2{
    margin-top: 50px;
}

h1{
    color: rgb(188, 228, 235);
    font-size: 100px;
}
p {
    color: rgb(219, 247, 252);
    font-size: 15px;
    line-height: 15px;

}
.card {
    width: 170px;
    height: 200px;
    display: inline-block;
    border-radius: 10px;
    padding: 15px 25px;
    box-sizing: border-box;
    margin: 10px 15px;
    background-position: center;
    background-size: cover;
    box-shadow: 5px 3px 8px rgb(112, 112, 112);
    transition: transform 0.5s;
    
}

.card1{
    background-image: url({% block bgPlace1%} {%endblock%} );
}
.card2{
    background-image: url({% block bgPlace2%} {%endblock%});
}
.card3{
    background-image: url({% block bgPlace3%} {%endblock%});
}
.card4{
    background-image: url({% block bgPlace4%} {%endblock%});
}

.card:hover{
    transform: translateY(-10px);
    
}
h5{
    color: #b4e6ef;
    font-size: 12px;
    text-shadow:  2px 2px 3px #222222;
}

</style>
{% endblock %}

{% block bgImage%}{% endblock %}

{% block content %}
<div class="row">
    <div class="col col2">
    <h1>{% block catchyPhrase %} {% endblock %}</h1>
    <p>{%block details%}{% endblock %}</p>
    </div>
    <div class="col">
        <div class="card card1">
            <h5>{%block place1%} {% endblock %}</h5>
        </div>
        <div class="card card2">
        <h5>{%block place2%} {% endblock %}</h5>
        </div>
        <div class="card card3">
        <h5>{%block place3%} {% endblock %}</h5>
        </div>
        <div class="card card4">
        <h5>{%block place4%} {% endblock %}</h5>
        </div>
        
    </div>
</div>


{% endblock %}

Tourism/cities_app/templates/cities_app/hail_page.html
{% extends  'cities_app/base2.html' %}
<!-- Page Name -->
{% block title %} Hail City {% endblock%}
<!-- background image -->
{% block bgImage%} https://www.abouther.com/sites/default/files/2021/07/02/saudi_arabia_hail_region.jpg {% endblock %}
<!-- Main Phrase -->
{% block catchyPhrase %}The City of Hail surrounded and full of history{% endblock %}
<!-- Sub Phrase -->
{% block details %}Nestled between Mount Shammer to the north and Mount Salma to the south, the city of <span style="color: #00b6d6;">Hail</span> was once the capital of all the Arabian Desert and home to legends like Hatim Al Tai, the Arabian poet whose altruism earned him spots in stories like “One Thousand and One Nights” (also known as “Arabian Nights”).{% endblock %}
<!-- Places Pictures -->
{% block bgPlace1%}https://resizer.wafyapp.com/?source=https://prod-wafy-api.s3.eu-central-1.amazonaws.com/images/articles/683-20210502192528-8826931.jpg&width=900 {%endblock%}
{% block bgPlace2%}https://scontent.fruh4-6.fna.fbcdn.net/v/t31.18172-8/15937063_10154264663683067_3079166276980970659_o.jpg?_nc_cat=107&ccb=1-7&_nc_sid=2c4854&_nc_ohc=-SsRy71-yu8AX_1kqS6&_nc_ht=scontent.fruh4-6.fna&oh=00_AfDv1WWEbqtvYaHVRZsdATin8H581dD5Q9iEPqulYbU93g&oe=6499BE14{%endblock%}
{% block bgPlace3%}/static/images/soukHail.jpg{%endblock%}
{% block bgPlace4%}https://i2.wp.com/mytrip.sa/wp-content/uploads/2018/10/%D8%B5%D9%88%D8%B1-%D8%A7%D9%84%D9%85%D9%88%D9%82%D8%B9-%D8%A7%D9%84%D8%AC%D8%AF%D9%8A%D8%AF.jpg{%endblock%}
<!-- Places Names -->
{%block place1%}Al-Qishla Castle{% endblock %}
{%block place2%}Discovery{% endblock %}
{%block place3%}Hail Souk{% endblock %}
{%block place4%}Al-Samraa View{% endblock %}

Tourism/cities_app/templates/cities_app/home_page.html
{% extends  'cities_app/base1.html' %}
<!-- Page Name -->
{% block title %} Tourism Website {% endblock %}
<!-- background image -->
{% block bgImage %} /static/images/mainPage.jpg {% endblock %}
{% block head %} 

{% endblock %}
{% block content %}
    <!-- Main Phrase -->
    <h1>Discover The Country Of Cultures</h1>
    <div class="vid">
        <div class="phrase"></div>
    <p>Take a look of what you can visit in<span style="color: #00b6d6;"> Saudi Arabia</span></p>
    <iframe class="video" width="560" height="315" src="https://www.youtube.com/embed/kDqTPT1SQbU" title="Welcome to Saudi Tourism Saudi Arabia" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </div>
{% endblock %}

Tourism/cities_app/templates/cities_app/mekkah_page.html
{% extends  'cities_app/base2.html' %}
<!-- Page Name -->
{% block title %} Mekkah City {% endblock%}
<!-- background image -->
{% block bgImage%} /static/images/mekkahCity.jpg {% endblock %}
<!-- Main Phrase -->
{% block catchyPhrase %}The City that Embraces the Qiblah of Muslims{% endblock %}
<!-- Sub Phrase -->
{% block details %}<span style="color: #00b6d6;">Mekkah</span> welcomes millions of Muslims who go to Hajj or Umrah.  It is the purest spot on Earth, and the holiest Islamic destination in the world, and it includes historical destinations that reveal immortal stories that left their mark in Islamic history.{% endblock %}
<!-- Places Pictures -->
{% block bgPlace1%}/static/images/grandMosque.jpg{%endblock%}
{% block bgPlace2%}/static/images/clockTower.jpg{%endblock%}
{% block bgPlace3%}/static/images/thowrMountain.jpg{%endblock%}
{% block bgPlace4%}/static/images/bayahMosque.jpg{%endblock%}
<!-- Places Names -->
{%block place1%}The Grand Mosque{% endblock %}
{%block place2%}ClockTower Museum{% endblock %}
{%block place3%}Thowr Mountain{% endblock %}
{%block place4%}Bay'ah Mosque{% endblock %}

Tourism/cities_app/templates/cities_app/riyadh_page.html
{% extends 'cities_app/base2.html' %}
<!-- Page Name -->
{% block title %} Riyadh City {% endblock%}
<!-- background image -->
{% block bgImage%} /static/images/riyadhCity.jpg{% endblock %}
<!-- Main Phrase -->
{% block catchyPhrase %}Live the Modern Life<br>to its Fullest{% endblock %}
<!-- Sub Phrase -->
{% block details %}In the ever-growing and flourishing city of<span style="color: #00b6d6;"> Riyadh</span>, you will discover the birthplace of the Kingdom of Saudi Arabia, along with its historical treasures hidden in the old palaces that witnessed the founding of the kingdom.{% endblock %}
<!-- Places Pictures -->
{% block bgPlace1%}/static/images/soukAlZal.jpg{%endblock%}
{% block bgPlace2%}/static/images/kafdCity.jpg{%endblock%}
{% block bgPlace3%}/static/images/diriyah.jpg{%endblock%}
{% block bgPlace4%}/static/images/viaRiyadh.webp{%endblock%}
<!-- Places Names -->
{%block place1%}Souk Al-Zal{% endblock %}
{%block place2%}KAFD city{% endblock %}
{%block place3%}DIRIYAH{% endblock %}
{%block place4%}VIA Riyadh{% endblock %}

Tourism/cities_app/templates/cities_app/test.html
{% extends  'cities_app/base2.html' %}
<!-- Page Name -->
{% block title %} Hail City {% endblock%}
<!-- background image -->
{% block bgImage%} /static/images/hailCity.jpg {% endblock %}
<!-- Main Phrase -->
{% block catchyPhrase %}The City of Hail surrounded and full of history{% endblock %}
<!-- Sub Phrase -->
{% block details %}Nestled between Mount Shammer to the north and Mount Salma to the south, the city of <span style="color: #00b6d6;">Hail</span> was once the capital of all the Arabian Desert and home to legends like Hatim Al Tai, the Arabian poet whose altruism earned him spots in stories like “One Thousand and One Nights” (also known as “Arabian Nights”).{% endblock %}
<!-- Places Pictures -->
{% block bgPlace1%}/static/images/qishlaCastle.jpg{%endblock%}
{% block bgPlace2%}/static/images/discovery.jpg{%endblock%}
{% block bgPlace3%}/static/images/hailSouk.jpg{%endblock%}
{% block bgPlace4%}/static/images/samraaView.png{%endblock%}
<!-- Places Names -->
{%block place1%}Al-Qishla Castle{% endblock %}
{%block place2%}Discovery{% endblock %}
{%block place3%}Hai Souk{% endblock %}
{%block place4%}Al-Samraa View{% endblock %}