TourismProject/TourismProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main_app.urls")),
]

TourismProject/main_app/urls.py
from django.urls import path
from . import views

app_name = "main_app"

urlpatterns = [
    path("", views.home_page, name="home_page"),
    path("city/taif/", views.taif_page, name="taif_page"),
    path("city/riyadh/", views.riyadh_page, name="riyadh_page"),
    path("city/jeddah/", views.jeddah_page, name="jeddah_page"),
    path("mode/dark/", views.dark_mode, name="dark_mode"),
    path("mode/light/", views.light_mode, name="light_mode")

]

TourismProject/tourism/urls.py
from django.urls import path
from . import views
from .models import Videos

app_name="tourism"

urlpatterns=[
    path("", views.home_page,name="home_page"),
    path("city/riyadh",views.riyadh,name="riyadh_page"),
    path("city/makkah", views.makkah,name="makkah_page"),
    path("city/bisha", views.Bisha,name="bisha_page"),
    path("city/madinah",views.Madinah,name="madinah_page")

]

TourismProject/main_app/models.py
from django.db import models

# Create your models here.

class City(models.Model):
    city_name= models.CharField(max_length=100)
    discription= models.TextField()
    

TourismProject/tourism/models.py
from django.db import models

# Create your models here.
from embed_video.fields import EmbedVideoField

class Videos(models.Model):
    video = EmbedVideoField()  # same like models.URLField()

class Video_2(models.Model):
    video_2 = EmbedVideoField()

TourismProject/main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse


def home_page(request: HttpRequest):


    return render(request, "main_app/home.html")

def taif_page(request: HttpRequest):


    return render(request, "main_app/taif.html")

def jeddah_page(request: HttpRequest):


    return render(request, "main_app/jeddah.html")

def riyadh_page(request: HttpRequest):


    return render(request, "main_app/riyadh.html")

def dark_mode(request:HttpRequest):
   
    response = redirect("main_app:home_page")
    response.set_cookie("mode", "dark")

    return response

def light_mode(request:HttpRequest):
    
    response = redirect("main_app:home_page")
    response.set_cookie("mode", "light")

    return response

TourismProject/tourism/views.py
from django.shortcuts import render
from django.http import HttpRequest
from .models import Videos
# Create your views here.

# def base(request):
#     videos =Videos.objects.all()
#     return render(request,"tourism/base.html", {'videos':videos})

def home_page(request:HttpRequest):
    videos =Videos.objects.all()

    return render(request,"tourism/home_page.html", {'videos':videos})

def riyadh(request:HttpRequest):
    videos =Videos.objects.all()
    return render(request,"tourism/riyadh.html", {'videos':videos})

def makkah(request:HttpRequest):
    videos =Videos.objects.all()
    return render(request,"tourism/makkah.html", {'videos':videos})

def Bisha(request:HttpRequest):
    videos =Videos.objects.all()
    return render(request,"tourism/bisha.html", {'videos':videos})

def Madinah(request:HttpRequest):
    videos =Videos.objects.all()
    return render(request,"tourism/madinah.html", {'videos':videos})

 

TourismProject/main_app/templates/main_app/abha.html
{% extends  'main_app/base.html' %}
{% load static %}


{% block welcome %}
<p>Welcome to abha the highest peak in the Kingdom of Saudi Arabia</p>  
<p style="font-size: 30px;">Al-Dabab Walkway… A Few Steps Away from Wonder
    Part of the marvel of the trip to Abha, which is full of breath-taking natural sights, is seeing its fog that penetrates its mountains and touches its land in Al-Dabab Walkway, which spans over 7 km. This experience, amidst a panoramic painting that showcases the greenery of the Sarawat Mountains, is worth travelling for.
    Enjoy the view of the nature’s mountains in Al-Dabab walkway. Observe the wide terraced farm fields at a height of 2200 m on the edge of the Sarawat Mountains. Breathe in the clean mountain air whilst you take a stroll through the heavy fog. Enjoy the beautiful taste of the good life in the green landscapes in an experience where you will capture a countless number of pictures of Abha’s mesmerizing fog.</p>    
{% endblock %}

{% block pictures %}
<div class="hero">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        
        <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
    
        <div class="carousel-inner">
        <div class="item active">
            <img src="{% static 'images/abha_1.jpg' %}">
        </div>
    
        <div class="item">
            <img src="{% static 'images/abha_2.jpg' %}">
        </div>
    
        <div class="item">
            <img src="{% static 'images/abha_3.jpg' %}">
        </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
        </div>
</div>
{% endblock %}

{% block videos %}
<div class="container">
    <div class="embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="https://youtube.com/embed/rXt-QbcpbaU"></iframe>
    </div>
  </div>
{% endblock %}

TourismProject/main_app/templates/main_app/about.html
{% extends  'main_app/base.html' %}
{% load static %}

{% block tour %}
<p> Tourism project was established to support the growth of the travel and tourism sector by serving the needs of tourism companies and other commercial partners.</p>
{% endblock %}

TourismProject/main_app/templates/main_app/almadinah.html
{% extends  'main_app/base.html' %}
{% load static %}


{% block welcome %}
<p>Welcome to Al madinah the second holiest city of the Islamic religion</p>  
<p style="font-size: 30px;">Mount Uhud, where the second battle in the history of Islam took place.
    Religious sites have a special place among Muslims in appreciation of the events that they witnessed and changed the course of history. Mount Uhud is one of the most prominent of these places. With its towering stature, it witnessed the second battle of the Muslims against their enemies.
    Visiting Mount Uhud is an experience full of stories embraced by this historical place. The first Muslims, led by Prophet Mohammad – Peace be upon him - stood in one of the battles on the granite rocks of the Mount. The vegetation and trees that grow between and around the stones of the Mount give a lively feel and form a captivating landscape full of memories.</p>    
{% endblock %}

{% block pictures %}
<div class="hero">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        
        <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
    
        <div class="carousel-inner">
        <div class="item active">
            <img src="{% static 'images/madinah_1.jpg' %}">
        </div>
    
        <div class="item">
            <img src="{% static 'images/madinah_2.jpg' %}">
        </div>
    
        <div class="item">
            <img src="{% static 'images/madinah_3.jpg' %}">
        </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
        </div>
</div>
{% endblock %}

{% block videos %}
<div class="container">
    <div class="embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="https://youtube.com/embed/vo08wshdIaM"></iframe>
    </div>
  </div>
{% endblock %}

TourismProject/main_app/templates/main_app/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel= "stylesheet" href="{% static 'styles/main.css' %}">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <style>

        </style>
    </head>
    
    <body class="main_div" style="{% block dibbg %} background-image: url('static/images/background_1.jpg'); {% endblock %}">
        <div >    
            <div class="nav_bar">
                <a href="{% url 'main_app:home' %}">Home</a>
                <a href="{% url 'main_app:riyadhh' %}">Riyadh</a>
                <a href="{% url 'main_app:abha' %}">Abha</a>
                <a href="{% url 'main_app:mekkah' %}">Mekkah</a>
                <a href="{% url 'main_app:almadinah' %}">Al madinah</a>
            </div>
                
            <div class="welcome">
                {% block welcome %}
                
                {% endblock %}
            </div>
            <div class="pictures">
                {% block pictures %}
                
                {% endblock %}
            </div>
            <div class="videos"></div>
                {% block videos %}
                

                
                {% endblock %}
            </div>
            <div class="tour">
                {% block tour %}
                
                {% endblock %}
            </div>
            <div class="home_pictures">
                {% block home_pictures %}

                {% endblock %}
            </div>
            <div class="bottom_page">
                <div>
                    <p>Powered by</p>
                    <img src="{% static 'images/logo_1.webp' %}" class="logo">
                </div>
                <div class="ag">
                    <p>Cities</p>
                    <a href="{% url 'main_app:riyadhh' %}">Riyadh</a>
                    <a href="{% url 'main_app:abha' %}">Abha</a>
                    <a href="{% url 'main_app:mekkah' %}">Mekkah</a>
                    <a href="{% url 'main_app:almadinah' %}">Al madinah</a>
                </div>
                <div class="ag">
                    <a href="{% url 'main_app:contact' %}">contact us</a>
                </div>
                <div class="ag">
                    <a href="{% url 'main_app:about' %}">about us</a>
                </div>
            </div>
        </div>
    </body>
</html>

TourismProject/main_app/templates/main_app/contact.html
{% extends  'main_app/base.html' %}
{% load static %}

{% block tour %}

<title>How To Connect</title>
<p>Send us a message <br> Abdulaziz-A1997@hotmail.com</p>

{% endblock %}

TourismProject/main_app/templates/main_app/home.html
{% load static %}
<!DOCTYPE html>


<html>
    <head>
        <title>{% block title %} Home Page {% endblock %}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link rel="stylesheet" href="{% static 'styles/main.css' %}" />
        

    
        <style>
/*         {% if request.COOKIES.mode == "light"%}
        <div>

        </div>
        {% else %}
        <div>

        </div>
        {% endif %} */
        * {
            margin:0px;
            padding:0px;
            font-family: 'Fira Sans', sans-serif;
            text-decoration: none;
            font-size: 1.3rem;
        }

        .container {
            display: flex;
            flex-direction: column;
            justify-content: start;
            row-gap: 2.5rem;
            /* background-image: url("{% block bgImage %}/static/images/mountains.jpg{% endblock %}"); */
            background-size: contain;
            background-repeat: no-repeat;
            min-height: 100vh;
            padding: 18px 35px;
            background-color: wheat;
        }


        .nav-bar{
            color: black;
            display: flex;
            flex-direction: row;
            justify-content: space-evenly;
            column-gap: 25px;
            align-items: center;
            background-color: lightyellow;
            border-radius: 40px;
            padding: 25px 45px;
            
        }
        .dark {
            color: white;
            background-color: black;
        }

        .dark .nav-bar {
            background-color: darkgray;
            color: white;
        }


        .dark .nav-bar a:link, .dark .nav-bar a:visited, .dark a:link, .dark a:visited, .dark span {
            color : white;
        }

        .dark .container{
            display: flex;
            flex-direction: column;
            justify-content: start;
            row-gap: 2.5rem;
            /* background-image: url("{% block bgImageDark %}/static/images/night-riyadh.jpg{% endblock %}"); */
            background-size: contain;
            background-repeat: no-repeat;
            min-height: 100vh;
            padding: 18px 35px;
            background-color: black;
        }


        * {box-sizing: border-box}
        body {font-family: Verdana, sans-serif; margin:0}
        .mySlides {display: none}
        img {vertical-align: middle;}

        /* Slideshow container */
        .slideshow-container {
        max-width: 1000px;
        position:relative;
        margin:auto;
        border-radius: 20px;
        overflow: hidden;


        }

        /* Next & previous buttons */
        .prev, .next {
        cursor: pointer;
        position: absolute;
        top: 50%;
        width: auto;
        padding: 16px;
        margin-top: -22px;
        color: white;
        font-weight: bold;
        font-size: 18px;
        transition: 0.6s ease;
        border-radius: 0 3px 3px 0;
        user-select: none;
        }

        /* Position the "next button" to the right */
        .next {
        right: 0;
        border-radius: 3px 0 0 3px;
        }

        /* On hover, add a black background color with a little bit see-through */
        .prev:hover, .next:hover {
        background-color: rgba(0,0,0,0.8);
        }

        /* Caption text */
        .text {
        color: #f2f2f2;
        font-size: 15px;
        padding: 8px 12px;
        position: absolute;
        bottom: 8px;
        width: 100%;
        text-align: center;
        }

        /* Number text (1/3 etc) */
        .numbertext {
        color: #f2f2f2;
        font-size: 12px;
        padding: 8px 12px;
        position: absolute;
        top: 0;
        }

        /* The dots/bullets/indicators */
        .dot {
        cursor: pointer;
        height: 15px;
        width: 15px;
        margin: 0 2px;
        background-color: #bbb;
        border-radius: 50%;
        display: inline-block;
        transition: background-color 0.6s ease;
        }

        .active, .dot:hover {
        background-color: #717171;
        }

        /* Fading animation */
        .fade {
        animation-name: fade;
        animation-duration: 1.5s;
        }

        @keyframes fade {
        from {opacity: .4} 
        to {opacity: 1}
        }

        /* On smaller screens, decrease text size */
        @media only screen and (max-width: 300px) {
        .prev, .next,.text {font-size: 11px}
        }

        </style>
    {% block head %}

    {% endblock %}
    </head>
    <body class="{% if request.COOKIES.mode == 'dark' %} dark {%endif%}"></body>


    <div class="container">

        <div class="nav-bar">
            <a href="/">Home</a>
            <a href="/city/taif">Taif</a>
            <a href="/city/riyadh">Riyadh</a>
            <a href="/city/jeddah">Jeddah</a>
        </div>

        <div class="right-nav">

            {% if request.COOKIES.mode == "light"%}
            <div>
                <a href="{% url 'main_app:dark_mode' %}"><span class="material-symbols-outlined">dark_mode</span></a>
            </div>
            {% else %}
            <div>
                <a href="{% url 'main_app:light_mode' %}"><span class="material-symbols-outlined">light_mode</span></a>
            </div>
            {% endif %}
        </div>

        {% block content %}
        <p>
            Saudi Arabia is an incredible country that has been open to tourists since 2019. 
            It is best known for being home to two of the most sacred cities in Islam, Makkah and Madinah. 
                        Here are some reasons why you should consider visiting Saudi Arabia:
            <ol>
            <li> A Spiritual Sanctuary: Two of Islam’s holiest cities are situated in Saudi Arabia: 
                Mecca and Medina, which are revered by over 1 billion Muslims.</li>
            <li> Mesmerizing Pre-Islamic History: Saudi Arabia is home to some of the most fascinating 
            discoveries that changed the face of history.</li>
            <li>Endless Diversity: From the Red Sea coast to the mountains of Asir, 
                Saudi Arabia is a land of contrasts and diversity.</li> 
            <li> Awe-Inspiring Scuba Diving: The Red Sea is one of the best places in the world for scuba diving.</li>
            <li>A Gastronomical Paradise: Traditional Arabic food is one of 
                the most loved and revered cuisines in the world.</li> 
            </ol>
        </p>
        {% endblock %}



<div class="slideshow-container">

    <div class="mySlides fade">
      <div class="numbertext">1 / 3</div>
      <img src="{% block slide1 %}/static/images/night-riyadh.jpg{% endblock %}" style="width:100%">
      <div class="text">Caption Text</div>
    </div>
    
    <div class="mySlides fade">
      <div class="numbertext">2 / 3</div>
      <img src="{% block slide2 %}/static/images/mountains.jpg{% endblock %}" style="width:100%">
      <div class="text">Caption Two</div>
    </div>
    
    <div class="mySlides fade">
      <div class="numbertext">3 / 3</div>
      <img src="{% block slide3 %}/static/images/night-riyadh.jpg{% endblock %}" style="width:100%">
      <div class="text">Caption Three</div>
    </div>
    
    <a class="prev" onclick="plusSlides(-1)">❮</a>
    <a class="next" onclick="plusSlides(1)">❯</a>
    
    </div>
    <br>
    
    <div style="text-align:center">
      <span class="dot" onclick="currentSlide(1)"></span> 
      <span class="dot" onclick="currentSlide(2)"></span> 
      <span class="dot" onclick="currentSlide(3)"></span> 
    </div>
    
    <script>
    let slideIndex = 1;
    showSlides(slideIndex);
    
    function plusSlides(n) {
      showSlides(slideIndex += n);
    }
    
    function currentSlide(n) {
      showSlides(slideIndex = n);
    }
    
    function showSlides(n) {
      let i;
      let slides = document.getElementsByClassName("mySlides");
      let dots = document.getElementsByClassName("dot");
      if (n > slides.length) {slideIndex = 1}    
      if (n < 1) {slideIndex = slides.length}
      for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";  
      }
      for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
      }
      slides[slideIndex-1].style.display = "block";  
      dots[slideIndex-1].className += " active";
    }
    </script>
    
   


    </div>


    </body>
</html>

TourismProject/main_app/templates/main_app/jeddah.html
{% extends  'main_app/home.html' %}
{% load static %}

{% block title %} Jeddah Page{% endblock %}

{% block content %}
    <h1>Jeddah - A seaside city filled with beauty</h1>
    <p> When you visit Jeddah, you will have the opportunity to witness a rich heritage celebrated by UNESCO.
        From “Historical Jeddah” to the antique designs of balconies, stone walkways and ancient sidewalks,
        this destination unearths secrets that have inspired artists, writers and visitors alike for hundreds of years. 
        Here, you will have a chance to see magnificent sunsets shimmering off the divine Red Sea shores as 
        well as having magical diving experiences featuring colorful coral reefs.
        Whether on land or under the sea, you won’t soon forget Jeddah’s many year-round splendors. </p>

    <a href="" class="btn">Video</a>
    <iframe width="966" height="411" src="https://www.youtube.com/embed/wD6Vip6zvsw" title="Jeddah - Saudi Arabia - Welcome to Arabia - Directors Cut" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

{% endblock %}
{% block slide1 %}/static/images/jeddah-night.jpeg{% endblock %}"
{% block slide2 %}/static/images/jeddah-2.jpeg{% endblock %}"
{% block slide3 %}/static/images/jeddah-3.jpeg{% endblock %}"

TourismProject/main_app/templates/main_app/riyadh.html
{% extends  'main_app/home.html' %}
{% load static %}

{% block title %} Riyadh Page{% endblock %}
{% block bgImageDark %}/static/images/night-riyadh.jpg{% endblock %}
{% block content %}
    <h1>Riyadh - Live the Modern Life to its Fullest </h1>
    <p> In the ever-growing and flourishing city of Riyadh, 
        you will discover the birthplace of the Kingdom of Saudi Arabia, 
        along with its historical treasures hidden in the old palaces that witnessed the founding of the kingdom. 
        It is a destination for tourists from all over the globe who wish to discover a world of shopping, 
        entertainment and business. The malls offer the most exciting shopping experience, 
        and the sand dunes combined with the brightest stars in the sky present the most magical experience in nature. 
        It is an environment full of a natural variety and unique characteristics that are intriguing for explorers. 
        On the other side of the bustling city, you can enjoy a variety of experiences in luxurious restaurants that 
        offer their special services, and their elaborate international dishes. Simultaneously, the local Riyadh 
        restaurants will tempt you with their authentic flavors and blend of spices originating from Saudi culture. 
        Everyone is happy in the city of Riyadh where the biggest cultural events are always celebrated. 
        Endless entertainment destinations are always emerging, for the city’s visitors to have intriguing and renewing 
        experienes.</p>

        <iframe width="966" height="411" src="https://www.youtube.com/embed/35g7UMVbfPc" title="Riyadh  - Saudi Arabia - Welcome to Arabia - Directors Cut" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>          
        {% endblock %}
          {% block slide1 %}/static/images/night-riyadh.jpg{% endblock %}"
          {% block slide2 %}/static/images/riyadh-2.jpeg{% endblock %}"
          {% block slide3 %}/static/images/riyadh-3.jpeg{% endblock %}"

TourismProject/tourism/templates/tourism/base.html
{% load static %}
<!--  -->
{% load bootstrap5 %}
<!--  -->

<!DOCTYPE html>
<html>
  <head>
    <title>{% block title%} home page {%endblock%}</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
      crossorigin="anonymous"
    ></script>
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'styles/main.css' %}" />
  </head>
  <body>
    <div class="wrapper">
      <img
        src="{% block backgoundImage %} {%static 'images/img1.jpg'%} {% endblock %}"
        alt=""
      />
      <div class="content">
        <div class="header">
          <div class="logo">
            <img src="{% static 'icons/icon1.png'%}" alt="logo" />
            <p class="title">TOURISM</p>
          </div>
          <nav class="navmenu">
            <a href="{% url 'tourism:home_page'%}">Home</a>
            <a href="{% url 'tourism:riyadh_page'%}">riyadh</a>
            <a href="{% url 'tourism:makkah_page'%}">Makkah</a>
            <a href="{% url 'tourism:bisha_page'%}">Bisha</a>
            <a href="{% url 'tourism:madinah_page'%}">Madinah</a>
          </nav>
        </div>
        {% block content %}
        <!--  -->
        {% endblock %}
      </div>
    </div>
    <section class="section">
      <div class="slider">
        {% block slider%}
        <div id="hero-carousel" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-indicators">
            <button
              type="button"
              data-bs-target="#hero-carousel"
              data-bs-slide-to="0"
              class="active"
              aria-current="true"
              aria-label="Slide 1"
            ></button>
            <button
              type="button"
              data-bs-target="#hero-carousel"
              data-bs-slide-to="1"
              aria-label="Slide 2"
            ></button>
            <button
              type="button"
              data-bs-target="#hero-carousel"
              data-bs-slide-to="2"
              aria-label="Slide 3"
            ></button>
          </div>

          <div class="carousel-inner">
            <div class="carousel-item active c-item">
              <img
                src="{% block img_1%} {%endblock%}"
                class="d-block w-100 c-img"
                alt="Slide 1"
                width="300"
                height="500"
              />
              <div class="carousel-caption top-0 mt-4">
                <p class="mt-5 fs-3 text-uppercase">
                  Discover the hidden world
                </p>
                <h1 class="display-1 fw-bolder text-capitalize">
                  The Aurora Tours
                </h1>
                <button class="btn btn-primary px-4 py-2 fs-5 mt-5">
                  Book a tour
                </button>
              </div>
            </div>
            <div class="carousel-item c-item">
              <img
                src="{% block img_2%} {%endblock%}"
                class="d-block w-100 c-img"
                alt="Slide 2"
              />
              <div class="carousel-caption top-0 mt-4">
                <p class="text-uppercase fs-3 mt-5">The season has arrived</p>
                <p class="display-1 fw-bolder text-capitalize">
                  3 available tours
                </p>
                <button
                  class="btn btn-primary px-4 py-2 fs-5 mt-5"
                  data-bs-toggle="modal"
                  data-bs-target="#booking-modal"
                >
                  Book a tour
                </button>
              </div>
            </div>
            <div class="carousel-item c-item">
              <img
                src="{% block img_3%} {%endblock%}"
                class="d-block w-100 c-img"
                alt="Slide 3"
              />
              <div class="carousel-caption top-0 mt-4">
                <p class="text-uppercase fs-3 mt-5">Destination activities</p>
                <p
                  class="display-1 fw-bolder{%block bishaOpacity%} {%endblock%} text-capitalize"
                >
                  Go glacier hiking
                </p>
                <button
                  class="btn btn-primary px-4 py-2 fs-5 mt-5"
                  data-bs-toggle="modal"
                  data-bs-target="#booking-modal"
                >
                  Book a tour
                </button>
              </div>
            </div>
          </div>
          <button
            class="carousel-control-prev"
            type="button"
            data-bs-target="#hero-carousel"
            data-bs-slide="prev"
          >
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button
            class="carousel-control-next"
            type="button"
            data-bs-target="#hero-carousel"
            data-bs-slide="next"
          >
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        {%endblock%}
      </div>
      <!-- <div class="slider">
    </div> -->
    </section>
    <section class="video">{% block video%} {%endblock%}</section>
  </body>
</html>