Tourister/Saudi_Tourism/urls.py
from django.urls import path
from . import views


name_app = "Saudi_Tourism"

urlpatterns = [
    path("", views.home_page, name= "home_page"),
    path("city/abha/", views.abha_page, name= "abha_page"),
    path("city/alula/", views.alula_page, name= "alula_page"),
    path("city/mekkah/", views.mekkah_page, name= "mekkah_page"),
    path("city/riyadh/", views.riyadh_page, name= "riyadh_page"),

]

Tourister/Tourism/urls.py
from django.urls import path
from . import views

app_name = "Tourism"

urlpatterns = [    
    path("test/", views.test_page, name="test_page"),
    path("", views.home_page, name="home_page"),
    path("city/alula", views.alula_page, name="alula_page"),
    path("city/mekkah", views.mekkah_page, name="mekkah_page"),
    path("city/dammam", views.dammam_page, name="dammam_page"),
    path("city/neom", views.neom_page, name="neom_page"),

]

Tourister/Tourister/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Tourism.urls")),
]

Tourister/mainApp/urls.py
from . import views
from django.urls import path

app_name = 'mainApp'

urlpatterns = [
    path('',views.homePage, name='homePage'),
    path('about',views.aboutPage, name='aboutPage'),
    path('contact',views.contactPage, name='contactPage'),
    path('gallery/', views.galleryPage, name='galleryPage'),
    path('gallery/city-gallery', views.gallerySinglePage, name='gallerySinglePage'),
    path('city/Riyadh/', views.riyadhPage, name='riyadhPage'),
    path('city/Makkah/', views.makkahPage, name='makkahPage'),
    path('city/AlUla/', views.alulaPage, name='alulaPage'),
    path('city/Abha/', views.abhaPage, name='abhaPage')
    
    
]

Tourister/main_app/urls.py
from django.urls import path
from . import views

app_name= "main_app"

urlpatterns=[
    path('',views.home_page, name="home_page"),
    path('city/Riyadh/',views.riyadh_page,name="riyadh_page"),
    path('city/Abha/',views.abha_page,name="abha_page"),
    path('city/Makka/',views.makka_page,name="makka_page"),
    path('city/AlOla/',views.alola_page,name="alola_page"),
]

Tourister/tourism_app/urls.py
from django.urls import path
from . import views

app_name = 'tourism_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('city/', views.city, name='city'),
    path('riyadh/',views.riyadh,name='riyadh'),
    path('city/abha/',views.abha,name='abha'),
    path('city/makkah/',views.makkah,name='makkah'),
    path('city/alula/',views.alula,name='alula'),

]

Tourister/Saudi_Tourism/views.py
from django.shortcuts import render, resolve_url
from django.http import HttpRequest, HttpResponse


# Create your views here.

def home_page(request:HttpRequest):

    return render(request, "Saudi_Tourism/home_page.html")

def abha_page(request:HttpRequest):

    
    return render(request, "Saudi_Tourism/abha.html")

def alula_page(request:HttpRequest):

    return render(request, "Saudi_Tourism/alula.html")

def mekkah_page(request:HttpRequest):

    return render(request, "Saudi_Tourism/mekkah.html")

def riyadh_page(request:HttpRequest):

    return render(request, "Saudi_Tourism/riyadh.html")

Tourister/Tourism/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse 


# Create your views here.

def test_page(request: HttpRequest):
    return render(request, "Tourism/test_page.html")

def home_page(request: HttpRequest):
    return render(request, "Tourism/home_page.html")

def alula_page(request: HttpRequest):
    return render(request, "Tourism/alula_page.html")

def mekkah_page(request: HttpRequest):
    return render(request, "Tourism/mekkah_page.html")

def dammam_page(request: HttpRequest):
    return render(request, "Tourism/dammam_page.html")

def neom_page(request: HttpRequest):
    return render(request, "Tourism/neom_page.html")

Tourister/mainApp/views.py
from django.shortcuts import render
from django.http import HttpRequest

# Create your views here.
def homePage(request:HttpRequest):
    return render(request,'mainApp/index.html')

def aboutPage(request: HttpRequest):
    return render(request, 'mainApp/about.html')


def contactPage(request: HttpRequest):
    return render(request, 'mainApp/contact.html')

def galleryPage(request:HttpRequest):
    return render (request, 'mainApp/gallery.html')

def gallerySinglePage(request:HttpRequest):
    return render (request,'mainApp/gallery-single.html')

def riyadhPage(request:HttpRequest):
    return render (request,'mainApp/riyadh.html')

def makkahPage(request:HttpRequest):
    return render (request,'mainApp/makkah.html')

def alulaPage(request:HttpRequest):
    return render (request,'mainApp/alula.html')

def abhaPage(request:HttpRequest):
    return render (request,'mainApp/abha.html')

Tourister/main_app/views.py
from django.shortcuts import render
from django.shortcuts import resolve_url

from django.http import HttpRequest,HttpResponse
# Create your views here.

def home_page(request:HttpRequest):

    return render(request,"main_app/home.html")

def riyadh_page(request:HttpRequest):
    return render(request, "main_app/riyadh.html")

def abha_page(request:HttpRequest):
    
    return render(request, "main_app/abha.html")

def makka_page(request:HttpRequest):
    
    return render(request, "main_app/makka.html")

def alola_page(request:HttpRequest):
    
    return render(request, "main_app/alola.html")

Tourister/tourism_app/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'tourism_app/home.html')

def city(request):
    return render(request, 'tourism_app/city.html')

def riyadh(request):
    return render(request, 'tourism_app/riyadh.html')

def abha(request):
    return render(request, 'tourism_app/abha.html')

def makkah(request):
    return render(request, 'tourism_app/makkah.html')

def alula(request):
    return render(request, 'tourism_app/alula.html')

Tourister/main_app/templates/main_app/alula.html
{% extends 'main_app/index.html' %}
{% load static %}

{% block title %} Tourism in Alula city {% endblock %}

{% block video %}
    <video autoplay loop muted plays-inline src="{% static 'video/Alula.mp4' %}" class="video"></video>
{% endblock %}

{% block content %}
    <div class="content">
        <h1 class="left">AlUla <br> city</h1>
        <p class="left">A city in the Medina region.</p>
        <div class="links left">
            <a href="{% url 'main_app:home_page' %}#city" class="free-img">Cities</a>
        </div>
    </div>
{% endblock %}

{% block content2 %}
    <section id="city" class="cities">
        <div class="row">
            <div class="cities-col">
                <img src="{% static 'img/alula1.jpg' %}">
            </div>
            <div class="cities-col">
                <img src="{% static 'img/alula2.jpg' %}">
            </div>
            <div class="cities-col">
                <img src="{% static 'img/alula3.jpg' %}">
            </div>
        </div>
        <div class="row">
            <div class="cities-col">
                <img src="{% static 'img/alula4.jpg' %}">
            </div>
            <div class="cities-col">
                <img src="{% static 'img/alula5.jpg' %}">
            </div>
            <div class="cities-col">
                <img src="{% static 'img/alula6.jpg' %}">
            </div>
        </div>
    </section>
{% endblock %}

Tourister/main_app/templates/main_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Tourister{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alkatra:wght@700&family=Dosis:wght@600&family=Pangolin&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,700,0,200" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <script src="{% static 'js/script.js'%}" defer></script>
    <style>
      .material-symbols-outlined {
          font-variation-settings:
          'FILL' 0,
          'wght' 400,
          'GRAD' 0,
          'opsz' 48
        }

        *{
            padding: 0px;
            margin: 0px;
            text-decoration: none;
        }
        .container{
          background-image: url("{%block image%}{%static 'images/bg.jpeg'%}{%endblock%}");
          background-size: cover;          
            display: flex;
            flex-direction: column;
            justify-content: start;
            row-gap: 2.5rem;
            color: #373e24;
            background-color: #d9eccc;
            min-height: 100vh;
            padding: 45px 25px;
            
        }
        .nav{
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: center;
            position: fixed;
            top: 0px;
            right: 0px;
            left: 0px;
            height: 10vh;
            background-color:rgba(53, 72, 49, 0.826);           
            padding: 0px 15px;
            box-shadow: 0px 5px 10px rgb(99, 99, 99);
            font-family: 'Alkatra', cursive;
            font-family: 'Dosis', sans-serif;
            font-family: 'Pangolin', cursive;
            z-index: 3;
        }
        .logo{
          display: flex;
          flex-direction: row;
            margin: 0px;
            padding:0px;
            align-items: center;
            border-radius: 25px; 
            width:100%;
            height:3rem;  
            color: #d9eccc;
            font-size: 20pt;
        }
        .nav-bar{
            align-items: center;
            display: flex;
            justify-content: space-evenly;
            flex-direction: row;
            column-gap: 23rem;
            padding: 20px;
        }

        ul{
          display: flex;
          flex-direction: row;
          column-gap: 20px;
          list-style: none;
          border-radius: 20px;
          align-items: center;
        }
        ul li{
          display: inline-block; 
          position: relative;
        }
        ul li a{
          align-self: center;
          font-size: 14pt;
          border-radius: 20px;
          padding: 10px 20px;
          display: flex;
          flex-direction: row;
          justify-content: center;
          column-gap: 10px;
          color: #f7f9f5;
          text-align: center;
          
        }
        ul li ul.nav-dropdown li{
          display: block;
        }
        ul li ul.nav-dropdown{
          
          width: 100%;
          background-color: rgba(63, 88, 58, 0.826);
          position: absolute;
          z-index: 999;
          display: none;
        }
        ul li a:hover{
          background-color: #cae0ba;
          color: #121610;
        }
        ul li:hover ul.nav-dropdown{
          display: block;
        }
        .signin-search{
          display: flex;
          flex-direction: row;
          column-gap: 10px;
          align-items: center;
          text-decoration: none;          
        }
        .signin-search a{
          color: #d9eccc;
        }
        .signin-search a:hover{
          color: #121610;
        }
        .content{
          display: flex;
          flex-direction: column;
          align-items: center;
          row-gap: 3rem;
          justify-content: start;
          margin: 25px;
          padding: 35px;
          min-height: 100vh;
          font-family: 'Alkatra', cursive;
          font-family: 'Domine', serif;
          font-family: 'Dosis', sans-serif;
          font-family: 'Titillium Web', sans-serif;
        }
        h1{
          font-size: 50pt;
        }
        p{
          font-size: 16pt;
        }
        h2{
          font-size: 20pt;
        }

        .footer{
          display: flex;
          flex-direction: row;
          justify-content: space-between;
          align-items: center;
          position: fixed;
          bottom: 0px;
          background-color: #f0fde8e6;
          left: 0px;
          right: 0px;
          height: 5vh;
          padding: 5px 3px;
          font-family: 'Alkatra', cursive;
          font-family: 'Dosis', sans-serif;
          font-family: 'Pangolin', cursive;
          z-index: 999;
        }

        .cotactUs{
          display: flex;
          flex-direction: row;
          justify-content: space-evenly;
          align-items: center;
          column-gap: 5px;

        }
        .cotactUs ul{
          
          list-style-type: none;
          margin: 0;
          padding: 0;
          column-gap: 10px;
        }
        .cotactUs li{
          justify-content: space-evenly;
          float: left;
        }
        .cotactUs li a{
          display: block;
          color: white;
          text-align: center;
          padding: 5px 10px;
          margin: 5px 7px;
          text-decoration: none;
          border-radius: 50%;
        }

        .fa-twitter {  
          background: #55ACEE;  
          color: white;  
        } 
        .fa-instagram {  
          background: #605184;  
          color: white;  
        }  
        .fa-facebook {  
          background: #2a4377;  
          color: white;  
        } 
        .title{
          color: black;
          display: flex;
          flex-direction: column;
          font-weight: bold;
          row-gap: 20px;
          justify-content: start;
          align-items: start;
          width: 100%;
          padding: 10px;
        }
        /*gallery*/
        .gallery {box-sizing:border-box}

        /* Slideshow container */
        .slideshow-container {
          max-width: 80vw;
          position: relative;
          margin: 0px;
          object-fit: cover;
          object-position: center;

        }

        /* Make the images invisible by default */
        .Containers {
          display: none;
          width: 70vw;
        }

        /* forward & Back buttons */
        .Back, .forward {
          cursor: pointer;
          position: absolute;
          top: 48%;
          width: auto;
          margin-top: -23px;
          padding: 17px;
          color: grey;
          font-weight: bold;
          font-size: 19px;
          transition: 0.4s ease;
          border-radius: 0 5px 5px 0;
          user-select: none;
        }

        /* Place the "forward button" to the right */
        .forward {
          right: 0;
          border-radius: 4px 0 0 4px;
        }

        /*when the user hovers,add a black background with some little opacity */
        .Back:hover, .forward:hover {
          background-color: rgba(0,0,0,0.8);
        }

        /* Caption Info */
        .Info {
          color: #080808;
          font-size: 18px;
          font-weight: bold;
          padding: 10px 0px;
          position: absolute;
          bottom: 10px;
          width: 70vw;
          text-align: center;
          object-position: center;
          align-items: center;
          background-color: #e8e9db7a;
        }

        /* Worknumbering (1/3 etc) */
        .MessageInfo {
          color: #f2f2f3;
          font-size: 14px;
          padding: 10px 14px;
          position: absolute;
          top: 0;
        }

        /* The circles or bullets and indicators */
        .dots {
          cursor: pointer;
          height: 16px;
          width: 16px;
          margin: 0 3px;
          background-color: rgba(192, 207, 207, 0.863);
          border-radius: 50%;
          display: inline-block;
          transition: background-color 0.5s ease;
          object-position: center;
        }

        .enable, .dots:hover {
          background-color: #717161;
        }

        /* Faint animation */
        .fade {
          -webkit-animation-name: fade;
          -webkit-animation-duration: 1.4s;
          animation-name: fade;
          animation-duration: 1.4s;
        }

        @-webkit-keyframes fade {
          from {opacity: .5}
          to {opacity: 2}
        }

        @keyframes fade {
          from {opacity: .5}
          to {opacity: 2}
        }


    </style>
    {%block headstyle%}
    {%endblock%} 
</head>
<body>
<div class="container">
    <div class="nav">
        <div class="logo" ><!--<img  class="logo" src="{% static 'images/visitsaudi.avif' %}" alt="SaudiArabia" />-->Tourister</div>
        <div class="nav-bar">
            <ul >
              <li><a href="{% url 'main_app:home_page' %}">Home</a></li>
              <li><a href="#">AboutUs</a></li>
              <li><a href="#">Cities<span class="material-symbols-outlined">arrow_drop_down</span></a>
                  <ul class="nav-dropdown">
                    <li><a href="{% url 'main_app:riyadh_page' %}">Riyadh</a></li>
                    <li><a href="{% url 'main_app:alola_page' %}">Al-Ola</a></li>
                    <li><a href="{% url 'main_app:abha_page' %}">Abha</a></li>
                    <li><a href="{% url 'main_app:makka_page' %}">Makka</a></li>
                  </ul>
              </li>
            </ul>
            <div class="signin-search">
              <a href="#"><span class="material-symbols-outlined">search</span></a>
              <a href="#"><span class="material-symbols-outlined">person</span></a>
            </div>
        </div>
      </div>
    <div class="footer">
      <span>&copy; 2023 Tourister. All rights reserved.</span>
      <div class="cotactUs">Contact us:
        <ul>
          <li><a href="#" class="fa fa-twitter"></a></li>
          <li><a href="#" class="fa fa-instagram"></a></li>
          <li><a href="#" class="fa fa-facebook"></a></li>  
        </ul>
      </div>
    </div>
    <div class="content">

      {% block content %}
      <div class="title"></div>
      <div class="gallery">
      <div class="slideshow-container fade">

        <!-- Full images with numbers and message Info -->
        <div class="Containers">
          <div class="MessageInfo">1 / 3</div>
          <img src="{% static 'images/bg.jpeg' %}" style="width:100%">
          <div class="Info">First caption</div>
        </div>
      
        <div class="Containers">
          <div class="MessageInfo">2 / 3</div>
          <img src="{% static 'images/sahara1.jpeg' %}" style="width:100%">
          <div class="Info">Second Caption</div>
        </div>
      
        <div class="Containers">
          <div class="MessageInfo">3 / 3</div>
          <img src="{%static 'images/riyadh/blvr3.jpg'%}" style="width:100%">
          <div class="Info">Third Caption</div>
        </div>
      
        <!-- Back and forward buttons -->
        <a class="Back" onclick="plusSlides(-1)">&#10094;</a>
        <a class="forward" onclick="plusSlides(1)">&#10095;</a>
      </div>
      <br>
      
      <!-- The circles/dots -->
      <div style="text-align:center">
        <span class="dots" onclick="currentSlide(1)"></span>
        <span class="dots" onclick="currentSlide(2)"></span>
        <span class="dots" onclick="currentSlide(3)"></span>
      </div> 
      {% endblock %}


    </div>
  </div>
</div>

</body>
</html>

Tourister/main_app/templates/main_app/home.html
{% extends 'main_app/base.html' %}
{%load static%}
{%block title%}
Home page
{%endblock%}
{%block headstyle%}
<style>

  .phrase{
   display: flex;
   flex-direction: column;
   row-gap: 25px;
   justify-content: start;
  }
  .list-cities{
    background-color: rgba(250, 235, 215, 0.208);
    border-radius: 25px;
    width: 50%;
    display: flex;
    flex-direction: column;
    row-gap: 20px;
    justify-content: space-between;
    padding: 5px 20px;
    margin-top: 20px;
  }
  .paragraph{
    width: 70%;
    background-color: rgba(250, 235, 215, 0.4);
    border-radius: 20px;
    padding: 25px;
  }
  .paragraph p{
    font-size: 15pt;
  }
  .list-cities ul{
    display: flex;
    flex-direction: row;
    column-gap: 15px;
    text-decoration: none;
    color: black;
    border: 30px;
    border-color: antiquewhite;
  }
  .list-cities li a{
    
    color:antiquewhite;
    background-color:rgba(26, 39, 22, 0.642);
    
  }
  .list-cities li a:hover{
    color:rgb(12, 12, 12);
    background-color: rgba(250, 235, 215, 0.4);
    
  }
</style>
    {%endblock%} 
{% block content %}
<div class="phrase">
  <h1>Welcome to Tourister!</h1>
  <p><strong> We're here to help you discover the beauty of Saudi Arabia.</strong></p>
  <div class="paragraph">
    <p >Tourism in Saudi Arabia is a growing industry with significant potential. The country is home to a rich cultural heritage, stunning natural landscapes, and modern architectural marvels. Saudi Arabia has been investing heavily in developing its tourism industry, and in recent years, the government has launched several initiatives to attract tourists from around the world. Some of the most popular tourist destinations in Saudi Arabia include the historical city of Makkah, the cosmopolitan city of Riyadh, the ancient ruins of Madain Saleh, the sparkling waters of the Red Sea, and the breathtaking desert landscapes of the Empty Quarter. The government has also been working to improve infrastructure and develop new tourist attractions, such as the futuristic city of NEOM and the Qiddiya entertainment complex. With its diverse offerings and ambitious plans for growth, Saudi Arabia is poised to become a major player in the global tourism industry.</p>   
  </div>
  <div class="list-cities">
    <h2 >Explore our cities:</h2>
    <ul >
        <li><a href="{% url 'main_app:riyadh_page' %}">Riyadh</a></li>
        <li><a href="{% url 'main_app:alola_page' %}">Al-Ola</a></li>
        <li><a href="{% url 'main_app:abha_page' %}">Abha</a></li>
        <li><a href="{% url 'main_app:makka_page' %}">Makkah</a></li>
        
    </ul>
   </div>
</div>
  

{% endblock %}

Tourister/main_app/templates/main_app/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;600;700&display=swap">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0">

        {% load static %}
        <link rel="icon" sizes="192x192" href="{% static 'img/logo.png' %}">

        <title>{% block title %} Tourism in Saudi Arabia {% endblock %}</title>

        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/footer.css' %}">
        <link rel="stylesheet" href="{% static 'css/paragraph.css' %}">
        <link rel="stylesheet" href="{% static 'css/city.css' %}">

        <style>
            html{
                scroll-behavior: smooth;
            }
        </style>
    </head>
    <body>
        <div class="main">
            {% block video %} {% endblock %}
            <nav>
                <a href="{% url 'main_app:home_page' %}">
                    <img src="{% static 'img/logo.png' %}" alt="logo" class="logo">
                </a>
                <ul>
                    <li><a href="{% url 'main_app:home_page' %}">HOME</a></li>
                    <li><a href="{% url 'main_app:home_page' %}#city">CITIES</a></li>
                    <li><a href="#link">LINKS</a></li>
                </ul>
            </nav>
            {% block content %} {% endblock %}
        </div>
        
        {% block content2 %} {% endblock %}

        <section id="link" class="footer">
            <h4>About Us</h4>
            <p>We publish tourist attractions in Saudi Arabia with reliable sources.</p>
            <div class="links2">
                <div class="link2">
                    <a href="https://www.gcam.gov.sa/" target=”_blank”>General Commission for Audiovisual media</a>
                    <a href="https://www.gea.gov.sa/" target=”_blank”>General Entertainment Authority</a>
                    <a href="https://www.sta.gov.sa/ar/home" target=”_blank”>Saudi Tourism Authority</a>
                </div>
                <div class="link2">
                    <a href="https://museums.moc.gov.sa/" target=”_blank” target=”_blank”>Museums Commission</a>
                    <a href="https://mt.gov.sa/" target=”_blank”>Ministry of Tourism</a>
                    <a href="https://www.moc.gov.sa/ar" target=”_blank”>Ministry of Culture</a>
                </div>
            </div>
            <p>
                Made with by 
                <span class="material-symbols-outlined fa">favorite</span> 
                <a href="https://github.com/Yousef-Alsaadan" target=”_blank” id="my">Yousef-Alsaadan</a>
            </p>
        </section>
    </body>
</html>

Tourister/tourism_app/templates/tourism_app/home.html
{% extends 'tourism_app/base.html' %}
{% load static %}
{% block title %}Tourister - Tourism in Saudi Arabia{% endblock %}

{% block content %}
<h1>Popular destinations in Saudi Arabia</h1>
<div class="main-carousel">
  <div class="cell">
    <div class="card">
        <img src="{% static 'images/img8.jpg' %}" class="card-img-top" alt="Saudi Tourism">
        <div class="card-body">
            <h5 class="card-title">Tourism in saudi arabia</h5>
            <p class="card-text">Experience the enchanting beauty of Saudi Arabia. From mesmerizing landscapes to rich cultural heritage, Saudi Arabia offers a diverse range of attractions for every traveler. Explore ancient historical sites, immerse yourself in vibrant markets, and indulge in traditional Arabian hospitality.</p>
        </div>

    </div>
  </div>
  <div class="cell">
    <div class="card">
        <img src="{% static 'images/Riyadh.jpg' %}" class="card-img-top" alt="Saudi Tourism">
        <div class="card-body">
            <h5 class="card-title">Riyadh</h5>
            <p class="card-text">There are several reasons why people visit Riyadh and some of the famous places to explore in the city include:
Historical and Cultural Sites: Riyadh is home to historical and cultural landmarks that offer insights into Saudi Arabia's rich heritage. Some notable sites include Masmak Fortress, a symbol of the city's history, and the UNESCO-listed Diriyah Historical District, </p>
            <a href="{% url 'tourism_app:riyadh' %} " style="color:blue;text-decoration: underline;">Show more</a>
        </div>
    </div>
  </div>
  <div class="cell">
    <div class="card">
        <img src="{% static 'images/img7.jpg' %}" class="card-img-top" alt="Saudi Tourism">
        <div class="card-body">
            <h5 class="card-title">Makkah</h5>
            <p class="card-text">Islamic Pilgrimage: Saudi Arabia holds great significance for Muslims around the world as the birthplace of Islam. The holy cities of Mecca and Medina attract millions of pilgrims every year who come to perform Hajj or Umrah, the major Islamic pilgrimages. Visitors can witness the awe-inspiring Grand Mosque, the Kaaba, and other sacred sites.</p>
            <a href="{% url 'tourism_app:makkah' %}" style="color:blue;text-decoration: underline;">Show more</a>
        </div>
    </div>
  </div>
    <div class="card">
        <img src="{% static 'images/Abha.jpg' %}" class="card-img-top" alt="Saudi Tourism">
        <div class="card-body">
            <h5 class="card-title">Abha</h5>
            <p class="card-text">Abha is a city located in the southwestern region of Saudi Arabia, specifically in the Asir Province. It is known for its pleasant climate, beautiful landscapes, and cultural heritage. Here are some highlights about Abha.</p>
            <a href="{% url 'tourism_app:abha' %}" style="color:blue;text-decoration: underline;">Show more</a>
        </div>
    </div>
    <div class="card">
        <img src="{% static 'images/alula.jpg' %}" class="card-img-top" alt="Saudi Tourism">
        <div class="card-body">
            <h5 class="card-title">Alula</h5>
            <p class="card-text">Islamic Pilgrimage: Saudi Arabia holds great significance for Muslims around the world as the birthplace of Islam. The holy cities of Mecca and Medina attract millions of pilgrims every year who come to perform Hajj or Umrah, the major Islamic pilgrimages. Visitors can witness the awe-inspiring Grand Mosque, the Kaaba, and other sacred sites.</p>
            <a href="{% url 'tourism_app:alula' %}" style="color:blue;text-decoration: underline;">Show more</a>
        </div>
    </div>
</div>
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
<script type="text/javascript">
  $('.main-carousel').flickity({
  // options
  cellAlign: 'left',
  contain: true,
  pauseAutoPlayOnHover: false

});
</script>

{% endblock %}